### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 23bca283** [vtcbca/internal-exam-23bca283#2]
![image](https://github.com/user-attachments/assets/13fa2c83-a6ee-4c23-b471-97be1d6d1f1e)
error accuring in program

**Comment by amitvtcbb** [comment]
PUT PROPER IMAGE WITH FULL CODE. MAY BE ITS ERROR REGARDING IMPORTING MODULE. PLEASE CHECK CAN YOU IMPORT MODULE . "import writer" can you add this line?

**Comment by 23bca283** [comment]
The above file is not csv file it is a text file

**Comment by 23bca274** [comment]
You've to write " f.writelines " instead of " f.writeline " coz this will only used to print one line and " f.writelines " prints more than one line.

This may help you !

**Comment by 23bca283** [comment]
Thank you for suggestion
